### ISSUE TITLE
OpenCV installation issue

### ISSUE THREAD

**Issue by Unixsystem13** [CazzoPMX/KKPMX#1]
==== Processing cf_m_body
:: Running 'body' parser
['C:\\Users\\username\\Downloads\\kkpmx_core\\base_library.zip', 'C:\\Users\\username\\Downloads\\kkpmx_core\\cv2', 'C:\\Users\\username\\Downloads\\kkpmx_core\\lib-dynload', 'C:\\Users\\username\\Downloads\\kkpmx_core']
ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.
ERROR: something truly strange and unexpected has occurred, sorry!
...press ENTER to exit...

Occured when running the KKPMX 1.5.0 All-in-one converter on an unmodified KK export. Downgraded to KKPMX 1.4 and it now works fine.

**Comment by CazzoPMX** [comment]
Yeah, there was an issue with SciPy which after updating was gone.
