### ISSUE TITLE
===(4) Isolate protruding surfaces bug

### ISSUE THREAD

**Issue by X3gold** [CazzoPMX/KKPMX#10]
It always crashes without having created a pmx file I didn't notice before because I had taken figures with swimsuits

**Comment by CazzoPMX** [comment]
Reuploaded the Binaries, please try again. And thanks for telling me about these issues all the time, I appreciate it.

**Comment by X3gold** [comment]
I have now tested with the 1.8.2 and the only thing where it does not crash and a pmx file is created is everything under -- [0] Use best-guess defaults from KK

**Comment by CazzoPMX** [comment]
I think I found the issue, could you try again?

**Comment by X3gold** [comment]
Super worked with the latest without problems and thanks again for the fast support.
