### ISSUE TITLE
Hitomi Bug?

### ISSUE THREAD

**Issue by X3gold** [CazzoPMX/KKPMX#11]
I noticed that Hitomi does not use the overtex files when I use the all-in-one converter. The final result does not change for me as far as Hitomi is concerned.

**Comment by CazzoPMX** [comment]
Mhm.... does not happen for me. Could you maybe run the All-in-one converter with "moreinfo" activated (the 2nd option to yes) and tell me what the parameters for the hitomi calls are?

**Comment by X3gold** [comment]
==== Processing cf_m_hitomi_00
> Extends cf_m_hitomi_00#-35208
>--> Found 18 attributes to process
:: Running 'eye' parser
list index out of range

==== Processing cf_m_hitomi_00*1
> Extends cf_m_hitomi_00#-35210
>--> Found 18 attributes to process
:: Running 'eye' parser
list index out of range

[New text document.txt](https://github.com/CazzoPMX/KKPMX/files/8840812/New.text.document.txt)

**Comment by X3gold** [comment]
Thanks works now

**Comment by X3gold** [comment]
So I don't know if this is still a bug or not but despite this log

==== Processing cf_m_hitomi_00
> Extends cf_m_hitomi_00#-35208
>--> Found 18 attributes to process
:: Running 'eye' parser

=== Running overtex1(Eyes) Script with arguments:
-- C:\koikatsu_model\1\cf_m_hitomi_00.png
-- {\"highlight\": 1, \"offset\": \"(0.0, -0.05)\", \"scale\": \"(1.1, 1.1)\", \"showinfo\": true}
-- C:\koikatsu_model\1/extra\cf_m_hitomi_00_overtex1.png
-- {\"color\": [1, 1, 1], \"alpha\": 0.653}
-- C:\koikatsu_model\1/extra\cf_m_hitomi_00_overtex2.png
-- {\"color\": [0.9714286, 0.9714286, 0.9714286], \"alpha\": 0.3642857}
Wrote output image at
C:\koikatsu_model\1\cf_m_hitomi_00_pyHL.png

==== Processing cf_m_hitomi_00*1
> Extends cf_m_hitomi_00#-35210
>--> Found 18 attributes to process
:: Running 'eye' parser

=== Running overtex1(Eyes) Script with arguments:
-- C:\koikatsu_model\1\cf_m_hitomi_00+1.png
-- {\"highlight\": 1, \"offset\": \"(0.0, -0.05)\", \"scale\": \"(1.1, 1.1)\", \"showinfo\": true}
-- C:\koikatsu_model\1/extra\cf_m_hitomi_00_overtex1.png
-- {\"color\": [1, 1, 1], \"alpha\": 0.653}
-- C:\koikatsu_model\1/extra\cf_m_hitomi_00_overtex2.png
-- {\"color\": [0.9714286, 0.9714286, 0.9714286], \"alpha\": 0.3642857}
Wrote output image at
C:\koikatsu_model\1\cf_m_hitomi_00+1_pyHL.png

Is this original Hitomi png file
![cf_m_hitomi_00](https://user-images.githubusercontent.com/38250861/172184025-d577c2f7-83fc-4186-92e0-95547397c237.png)

After the all-in-one converter still without overtex 1 or overtex 2
![cf_m_hitomi_00_pyHL](https://user-images.githubusercontent.com/38250861/172184329-747b25a4-57db-479d-8cf1-589072124558.png)

I have taken the standard character named Haruno Chika taken.

**Comment by CazzoPMX** [comment]
Just for reference, which KK did you use? Normal, Party, Sunshine?

**Comment by X3gold** [comment]
Koikatsu! BetterRepack RX14 from here https://dl.betterrepack.com/public/
I'm from Germany and do not get the free variant, because here on Steam Hentai games are blocked

**Comment by CazzoPMX** [comment]
Same actually, what a coincedence.
Anyway, yes it was indeed a bug..... I just rounded the Highlight transparency to 0% or 100%.... fixed that.

**Comment by X3gold** [comment]
Yes now it works thanks for your hard work
