### ISSUE TITLE
No "Export" button!!!!

### ISSUE THREAD

**Issue by WuhuVoV** [CazzoPMX/KKPMX#14]
The installation path is correct, but there is no Export.
The computer system version is win11.
In what operating environment should kkpmx be used.
kk manger ：
Enabled Ture
location F:\KKS V1.08\BepInEx\plugins

**Comment by X3gold** [comment]
Windows 10
Koikatsu Sunshine [BetterRepack R6]

So for me, the export button is displayed.

![19-09-2022_18-51-24](https://user-images.githubusercontent.com/38250861/191071842-6f776331-fc31-468a-95e3-2f34d0dee587.jpg)

**Comment by WuhuVoV** [comment]
I also tried win10

**Comment by WuhuVoV** [comment]
Double system

**Comment by X3gold** [comment]
Well, I tried again with my laptop with Win 11 and as you wrote, it is not displayed. I guess it only works with Win 10 at the moment.

**Comment by WuhuVoV** [comment]
I also tried win10, but still didn't

**Comment by X3gold** [comment]
Are your plugins displayed on Win 10 and Win 11, by me not on Win 11, but only on Win 10.

![20-09-2022_15-16-56](https://user-images.githubusercontent.com/38250861/191268841-eb0f36ce-86fa-4bab-a846-7e5c782329e8.jpg)

**Comment by WuhuVoV** [comment]
I also don't show it on win11

**Comment by WuhuVoV** [comment]
I succeeded. I used the old plug-in first, and then I used the new plug-in to overwrite it

**Comment by X3gold** [comment]
Yes, I just tried it, it really works like that, it's interesting that I had to export a model first, only then the new plugin was recognized and all plugins are now also displayed, it's funny.

**Comment by WuhuVoV** [comment]
lol

**Comment by maidemao** [comment]
> 

which old plug-in did you use?
