### ISSUE TITLE
error Directory not Found

### ISSUE THREAD

**Issue by indras121** [CazzoPMX/KKPMX#15]
got this error message

[Error  : Unity Log] DirectoryNotFoundException: Could not find a part of the path "C:\koikatsu_model\Logging.log".
Stack trace:
System.IO.File.Delete (System.String path)
PmxExporter..cctor ()
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for PmxExporter

then the plugin cant work, how to fix this ?

**Comment by Haoming02** [comment]
I fixed it by maunally create the file there. _(ie. Create an empty text file and rename it to the exact same name.)_

**Comment by CazzoPMX** [comment]
Issue has been fixed with the new release
