### ISSUE TITLE
cf_m_body_overtex2 bug

### ISSUE THREAD

**Issue by X3gold** [CazzoPMX/KKPMX#17]
Again a bug this time it is like here https://github.com/CazzoPMX/KKPMX/issues/11 and namely at the body the cf_m_body_overtex2.png is not used means no pubic hair.

**Comment by CazzoPMX** [comment]
That's no bug, I simply never added it in the first place. I should do that at some point.

**Comment by X3gold** [comment]
Oh, that would explain it, of course. I assumed that because your plugin puts this cf_m_body_overtex2 texture in the extra folder.
