### ISSUE TITLE
All-in-one converter Error

### ISSUE THREAD

**Issue by X3gold** [CazzoPMX/KKPMX#2]
Hello, maybe you can help me, I keep getting this error message with KKPMX 1.5.2 All-in-one converter.

C:\koikatsu_model\4155\#generateJSON.json
==== Start Parsing ====
-- [Working Directory]: C:\koikatsu_model\4155
-- Parsing C:\koikatsu_model\4155\#generateJSON.json
[*] Lucy Aritos has no match in matJsn
[*] cf_m_sirome_00 has no match in matJsn
[*] cf_m_sirome_00 has no match in matJsn
[*] cf_m_bra_01 has no match in matJsn
Skip images (y/[n])?
> y

==== Processing cf_m_body
:: Running 'body' parser
['C:\\kkpmx_core\\base_library.zip', 'C:\\kkpmx_core\\cv2', 'C:\\kkpmx_core\\lib-dynload', 'C:\\kkpmx_core']
ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.
ERROR: something truly strange and unexpected has occurred, sorry!
...press ENTER to exit...

**Comment by More-Info** [comment]
kind of have same issue


==== Processing cf_m_body
:: Running 'body' parser
['C:\\Downloads\\kkpmx_core\\base_library.zip', 'C:\\Downloads\\kkpmx_core\\cv2', 'C:\\Downloads\\kkpmx_core\\lib-dynload', 'C:\\Downloads\\kkpmx_core']
ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.
ERROR: something truly strange and unexpected has occurred, sorry!
...press ENTER to exit...

**Comment by CazzoPMX** [comment]
Gwah, I should have checked the binary installation..... I'll look for a fix.

**Comment by CazzoPMX** [comment]
Should be fixed now.
