### ISSUE TITLE
Crash All-in-one converter 2.0.0

### ISSUE THREAD

**Issue by X3gold** [CazzoPMX/KKPMX#20]
Namely on some cards kkpmx_core 2.0.0 crashes, which in turn was not the case with kkpmx_core 1.8.4 and unfortunately the software immediately shuts down without a log being created.

Here are two cards that crash with kkpmx_core 2.0.0:

https://drive.google.com/file/d/1Ej9Dw8MzQpHrflm0OGIrh_qoM0QGeCYn/view?usp=drive_link
https://drive.google.com/file/d/1zEN5B6SDoz8UUwjGsJQSMJMoIIF0Ndq7/view?usp=drive_link

**Comment by X3gold** [comment]
![vlcsnap-2023-06-01-20h22m10s011](https://github.com/CazzoPMX/KKPMX/assets/38250861/002d1b91-2235-490d-9974-fbe685638155)

**Comment by X3gold** [comment]
I have noticed that whenever I export a certain clothing with your plugin via Coordinate, this error always happens with the 7: Parse Result from Plugin (image above).

coordinate: https://drive.google.com/file/d/1g23Ji7OgD2C8p_yV10WdDKcQPpFUAmlS/view?usp=sharing

**Comment by CazzoPMX** [comment]
I'll look into it o/

**Comment by CazzoPMX** [comment]
Please try it out, it should be fixed now ^-^

**Comment by X3gold** [comment]
Yes, it goes on now, unfortunately there is another error with the first card above.

![vlcsnap-2023-06-03-20h26m02s376](https://github.com/CazzoPMX/KKPMX/assets/38250861/ef4720c3-ee3b-4fc8-87b6-41dfb96cc96f)

**Comment by CazzoPMX** [comment]
Should be fixed now o7

**Comment by X3gold** [comment]
Super works now thanks for your work.
