### ISSUE TITLE
Knee looks broken

### ISSUE THREAD

**Issue by X3gold** [CazzoPMX/KKPMX#22]
I know you already described this in the Issues.md, but maybe you can add this tool **https://bowlroll.net/file/197410** there in the description. It's totally simple and with it you get the knee problem and other problems with the vmd and also the camera adapted to the figure, but it takes with the big vmd something until the conversion is ready.
![1](https://github.com/CazzoPMX/KKPMX/assets/38250861/6b76d4cc-ff2a-4553-9b05-18fc9f596b78)

**Comment by CazzoPMX** [comment]
Fancy, I'll have a look

**Comment by X3gold** [comment]
It's done is in the Discord channel under fag.
