### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by raynebc** [CazzoPMX/KKPMX#23]
I was going to try to message you on Twitter as you suggest, but your Twitter account is blocking messages.  Can that be allowed or do you prefer an alternate method of communication?

**Comment by CazzoPMX** [comment]
Ah thanks for telling me tha, I did not even know I had that

**Comment by raynebc** [comment]
When I try to send you a message, Twitter still says:  "You can no longer send messages to this person."

**Comment by CazzoPMX** [comment]
Heh.... Fine then. Just send me a Message at @thekaizo on Discord if you have it,
