### ISSUE TITLE
Duplicate texture data in folder

### ISSUE THREAD

**Issue by X3gold** [CazzoPMX/KKPMX#24]
Which files do you want to move to 'unused' folder?
1 = Do not move any, 2 = Move only top-level unused, 3 = Move all unused

Unfortunately, when I select 2 or 3, it always leaves textures that pmx has no use for back in the folder.

Standard
![09-06-2023_01-32-38](https://github.com/CazzoPMX/KKPMX/assets/38250861/5cf4f5b3-1d25-4092-ae93-2a2623204229)

With main textures from Grey's mesh exporter in extra folder
![09-06-2023_01-20-57](https://github.com/CazzoPMX/KKPMX/assets/38250861/84f68bbd-1c91-45bc-bd1c-3a76ddc647d4)

**Comment by CazzoPMX** [comment]
When I do "2-2-1", it sorts all textures correctly into either [tex] or [Unused]. Files from [Extras] are only sorted into [Tex] or kept where they are.

**Comment by X3gold** [comment]
So I tried it again with the default figure Haruno Chika (3 = Move all unused) but in the tex folder it looks like this with 2.0.1.1.

![14-06-2023_00-09-38](https://github.com/CazzoPMX/KKPMX/assets/38250861/641be827-d831-40fb-bfda-592086937277)

And with the 1.8.4 also (3 = Move all unused) it looks like this in the tex folder, with Haruno Chika

![14-06-2023_00-29-39](https://github.com/CazzoPMX/KKPMX/assets/38250861/e867796d-cbb8-4bd6-bfde-0e3cee6efb2e)

**Comment by X3gold** [comment]
I completely forgot to close this, I have now understood why some were duplicates.
