### ISSUE TITLE
Push as a morph

### ISSUE THREAD

**Issue by X3gold** [CazzoPMX/KKPMX#26]
Maybe you could add such an Add Push (http://diffeomorphic.blogspot.com/p/low-poly-section-version-15.html) function as a morph

Add Push

Replacing meshes with low-poly versions can sometimes give problems. Since the low-poly faces are larger the skin can poke through. The Add Push offers a quick fix for this. It adds a shapekey named Push which moves the vertices along the vertex normals.

Since the problem is more pronounced with tight-fitting clothes, Aiko has changed clothes to the basic wear, and we have made a quick low-poly with eight iterations of the top. There is clearly a problem with skin poking through.
![1](https://github.com/CazzoPMX/KKPMX/assets/38250861/b675a56a-544e-43c9-aa1d-ce9aafa5c4f3)

Use the Add Push tool to add a Push shapekey which moves vertices in the normal direction.

 
![2](https://github.com/CazzoPMX/KKPMX/assets/38250861/806173fd-296c-4881-a4e8-d5126a64d329)
 

Crank up the value a bit. The value 1.0 corresponds to moving the mesh 1.0 cm along the vertex normals, so in this case we pushed the top out 5.9 mm from the body. The problem with skin poking through has been reduced.

**Comment by CazzoPMX** [comment]
Mhm, I like how this works, I'll look into it.
Thanks for the tip

**Comment by X3gold** [comment]
Has been done with version 3.0.0, as I only suggested this because of AlphaMask.
