### ISSUE TITLE
Where to put the plugin?

### ISSUE THREAD

**Issue by dinoking27** [CazzoPMX/KKPMX#29]
im a beginner of koikatsu so im wonder where do i put the plugin folder and want to make the models to MMD for the first time

**Comment by X3gold** [comment]
Copy the plugins folder into the BepInEx folder if the folder is not there then you can install the **[HF patch](https://github.com/ManlyMarco/KK-HF_Patch/releases)** or use the **[BetterRepack](https://dl.betterrepack.com/public/) version** but you can also use the **[Bepinex Autoinstaller tool](https://f95zone.to/threads/bepinex-autoinstaller-v2-0-0.105441/)**.
