### ISSUE TITLE
textures don't get exported?

### ISSUE THREAD

**Issue by lunlune** [CazzoPMX/KKPMX#36]
i've run one of my custom made models in koi to the exporter plugin, only for get as result a model where almost all the textures are a transparent file. i thought it was a v+ shader issue, so i also ran the exporter with the default chikarin. the result being the same.
i'm missing something? (or maybe it's because i'm an evil creature that uses koikatsu with the saturation filter off?)

**Comment by X3gold** [comment]
Just ask here and you will usually get help very quickly https://discord.gg/HUexfg6f9E

**Comment by lunlune** [comment]
well, the solution is in the server (even if i ended to circurvent the issue by exporting manually all the textures) 
so, i can consider this solved👍
