### ISSUE TITLE
Face in raycast

### ISSUE THREAD

**Issue by X3gold** [CazzoPMX/KKPMX#6]
With version 1.6.1 All-in-one converter
![1](https://user-images.githubusercontent.com/38250861/166152495-2572c98e-c713-41d6-8e1d-552a1b151324.jpg)

With version 1.6.2 All-in-one converter
![2](https://user-images.githubusercontent.com/38250861/166152519-9d68cbfa-f394-444f-a5c5-5574735d3c5b.jpg)

I set it in PmxEditor so instead of setting everything to 1 under Diffuse, I set it all to the same value as the body, i.e. 0.5, then everything fit again.

Although I must say that when the body under diffuse everything is set to 1 I like so better is not so dark but is a matter of taste
![3](https://user-images.githubusercontent.com/38250861/166153356-98cc3dd7-4724-4470-88f0-6fa8bd259af6.jpg)

**Comment by CazzoPMX** [comment]
Just for completeness, what was the reason you closed it, now out of all days before?
