### ISSUE TITLE
No "Export" button

### ISSUE THREAD

**Issue by JapanYoshi** [CazzoPMX/KKPMX#7]
I did the following things to install the plugin:

1. Downloaded the latest 1.6.2 DLL file.
2. Installed it from KKManager.
3. Booted Koikatsu v5.1 with HF Patch v3.5.
4. Went into both Character Creation > Female and Character Creation > Male (separate times).

Expected behavior:

The instructions mention an "Export" button appearing on the top left corner of the game window.

Actual behavior:

No such button appeared.

**Comment by CazzoPMX** [comment]
I just found out that KKManager puts the DLL into [<KK>\BeplnEx].... where it will be ignored.
Go into that folder and move the DLL into the [plugins] subfolder [in total, in <KK>\BeplnEx\plugins] and try again.

**Comment by JapanYoshi** [comment]
I also figured out that the "Export" button only appears in the external CharaEditor instead of the character creator in Koikatsu.

**Comment by WuhuVoV** [comment]
Downloaded the latest 1.8.4 DLL file. No "Export" button.
The path is correct.
api1.32
win11

**Comment by WuhuVoV** [comment]
![1 (2)](https://user-images.githubusercontent.com/112870669/189577725-f609ffd6-20eb-4d3a-9525-0ab53e48be62.png)

**Comment by WuhuVoV** [comment]
![2](https://user-images.githubusercontent.com/112870669/189577883-47c8c76e-879a-4795-9881-8585be4d7061.png)

**Comment by WuhuVoV** [comment]
BepInEx_x64_5.4.21.0
