### ISSUE TITLE
1.8.0 All-in-one converter bug

### ISSUE THREAD

**Issue by X3gold** [CazzoPMX/KKPMX#8]
==== Processing cf_m_body
> Extends cf_m_body#-384132
>--> Found 29 attributes to process
:: Running 'body' parser
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

==== Processing cf_m_face_00
> Extends cf_m_face_00#-384128
>--> Found 29 attributes to process
:: Running 'face' parser
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
>--> [MissingFile(LineMask)]: C:\koikatsu_model\6195/extra\cf_m_face_00_LineMask.png

==== Processing cf_m_mayuge_00
> Extends cf_m_mayuge_00#-354532
>--> Found 9 attributes to process
:: Running 'color' parser

==== Processing cf_m_noseline_00
> Extends cf_m_noseline_00#-354534
>--> Found 8 attributes to process
:: Running 'color' parser

==== Processing cf_m_eyeline_00_up
> Extends cf_m_eyeline_00_up#-354536
>--> Found 9 attributes to process
:: Running 'color' parser

==== Processing cf_m_eyeline_down
> Extends cf_m_eyeline_down#-354540
>--> Found 9 attributes to process
:: Running 'color' parser

==== Processing cf_m_hitomi_00
> Extends cf_m_hitomi_00#-354518
>--> Found 18 attributes to process
:: Running 'eye' parser
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

==== Processing cf_m_hitomi_00*1
> Extends cf_m_hitomi_00#-354520
>--> Found 18 attributes to process
:: Running 'eye' parser
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

==== Processing cf_m_tang
> Extends cf_m_tang#-375264
>--> Found 25 attributes to process
:: Running 'acc' parser
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

==== Processing cf_m_emblem
> Extends cf_m_emblem#-377934
>--> Found 10 attributes to process
:: Running 'color' parser

==== Processing cf_m_top_sailor01_01
> Extends cf_m_top_sailor01_01#-377930
>--> Found 21 attributes to process
:: Running 'acc' parser
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

==== Processing cf_m_top_sailor05_02
> Extends cf_m_top_sailor05_02#-379970
>--> Found 21 attributes to process
:: Running 'acc' parser
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

==== Processing cf_m_top_sailor02_03
> Extends cf_m_top_sailor02_03#-381268
>--> Found 21 attributes to process
:: Running 'acc' parser
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

==== Processing cf_m_bot_skirt03
> Extends cf_m_bot_skirt03#-362394
>--> Found 21 attributes to process
:: Running 'acc' parser
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

==== Processing cf_m_top_swim14
> Extends cf_m_top_swim14#-383536
>--> Found 16 attributes to process
:: Running 'acc' parser
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

==== Processing cf_m_shorts_01
> Extends cf_m_shorts_01#-367000
>--> Found 16 attributes to process
:: Running 'acc' parser
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

==== Processing cf_m_socks_high02
> Extends cf_m_socks_high02#-369268
>--> Found 21 attributes to process
:: Running 'acc' parser
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

==== Processing cf_m_shoes_roafer01
> Extends cf_m_shoes_roafer01#-373766
>--> Found 21 attributes to process
:: Running 'acc' parser
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

==== Processing acs_m_bangle*1
> Extends acs_m_bangle@ca_slot08
>--> Found 26 attributes to process
:: Running 'acc' parser
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

==== Processing acs_m_ribbon*1
> Extends acs_m_ribbon@ca_slot14
>--> Found 26 attributes to process
:: Running 'acc' parser
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

==== Processing acs_m_bangle
> Extends acs_m_bangle@ca_slot09
>--> Found 26 attributes to process
:: Running 'acc' parser
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

==== Processing acs_m_ribbon
> Extends acs_m_ribbon@ca_slot15
>--> Found 26 attributes to process
:: Running 'acc' parser
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

==== Processing cf_m_hair_b_01_00
> Extends cf_m_hair_b_01_00@ca_slot06
>--> Found 21 attributes to process
:: Running 'hair' parser
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

==== Processing cf_m_hair_b_21_00
> Extends cf_m_hair_b_21_00@ca_slot07
>--> Found 21 attributes to process
:: Running 'hair' parser
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

==== Processing cf_m_hair_b_21_00*1
> Extends cf_m_hair_b_21_00@ca_slot07
>--> Found 21 attributes to process
:: Running 'hair' parser
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

==== Processing cf_m_hair_b_21_00*2
> Extends cf_m_hair_b_21_00@ca_slot07
>--> Found 21 attributes to process
:: Running 'hair' parser
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

==== Processing cf_m_hair_edgy*1
> Extends cf_m_hair_edgy@ca_slot10
>--> Found 21 attributes to process
:: Running 'hair' parser
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

==== Processing cf_m_hair_edgy
> Extends cf_m_hair_edgy@ca_slot11
>--> Found 21 attributes to process
:: Running 'hair' parser
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

==== Processing cf_m_hair_b_21_00*3
> Extends cf_m_hair_b_21_00@ca_slot12
>--> Found 21 attributes to process
:: Running 'hair' parser
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

==== Processing cf_m_hair_b_21_00*4
> Extends cf_m_hair_b_21_00@ca_slot12
>--> Found 21 attributes to process
:: Running 'hair' parser
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

==== Processing cf_m_hair_b_21_00*5
> Extends cf_m_hair_b_21_00@ca_slot12
>--> Found 21 attributes to process
:: Running 'hair' parser
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

==== Processing cf_m_hair_f_20_00
> Extends cf_m_hair_f_20_00@ca_slot13
>--> Found 21 attributes to process
:: Running 'hair' parser
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

==== Processing cf_m_hair_f_20_00*1
> Extends cf_m_hair_f_20_00@ca_slot16
>--> Found 21 attributes to process
:: Running 'hair' parser
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

==== Processing cf_m_hair_f_06_00
> Extends cf_m_hair_f_06_00@ca_slot17
>--> Found 21 attributes to process
:: Running 'hair' parser
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

==== Processing cf_m_hair_b_119_00
> Extends cf_m_hair_b_119_00@ca_slot18
>--> Found 21 attributes to process
:: Running 'hair' parser
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

==== Processing cf_m_hair_b_119_00*1
> Extends cf_m_hair_b_119_00@ca_slot18
>--> Found 21 attributes to process
:: Running 'hair' parser
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

==== Processing cf_m_hair_b_119_01
> Extends cf_m_hair_b_119_01@ca_slot18
>--> Found 21 attributes to process
:: Running 'hair' parser
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

==== Processing cf_m_hair_b_119_01*1
> Extends cf_m_hair_b_119_01@ca_slot18
>--> Found 21 attributes to process
:: Running 'hair' parser
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

==== Processing cf_m_hair_b_119_01*2
> Extends cf_m_hair_b_119_01@ca_slot18
>--> Found 21 attributes to process
:: Running 'hair' parser
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

==== Processing cf_m_hair_b_21_00*6
> Extends cf_m_hair_b_21_00@ca_slot19
>--> Found 21 attributes to process
:: Running 'hair' parser
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

==== Processing cf_m_hair_b_21_00*7
> Extends cf_m_hair_b_21_00@ca_slot19
>--> Found 21 attributes to process
:: Running 'hair' parser
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

==== Processing cf_m_hair_b_21_00*8
> Extends cf_m_hair_b_21_00@ca_slot19
>--> Found 21 attributes to process
:: Running 'hair' parser
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
==========
Additionally, these textures failed to generate:
-- ..\cf_m_body_pyDet.png
-- ..\cf_m_body_pyLin.png
-- ..\cf_m_body_pyOT1.png
-- ..\cf_m_face_00_pyDet.png
-- ..\cf_m_face_00_pyLin.png
-- ..\cf_m_hitomi_00_pyHL.png
-- ..\cf_m_hitomi_00+1_pyHL.png
-- cf_m_tang@ct_head_pyCol_pyDet.png
-- cf_m_tang@ct_head_pyCol.png
-- ..\cf_m_top_sailor01_01_pyDet.png
-- ..\cf_m_top_sailor05_02_pyDet.png
-- ..\cf_m_top_sailor02_03_pyDet.png
-- ..\cf_m_bot_skirt03_pyDet.png
-- ..\cf_m_top_swim14_pyDet.png
-- ..\cf_m_shorts_01_pyDet.png
-- ..\cf_m_socks_high02_pyDet.png
-- ..\cf_m_shoes_roafer01_pyDet.png
-- acs_m_bangle@ca_slot08_pyCol_pyDet.png
-- acs_m_bangle@ca_slot08_pyCol.png
-- acs_m_ribbon@ca_slot14_pyCol_pyDet.png
-- acs_m_ribbon@ca_slot14_pyCol.png
-- acs_m_bangle@ca_slot09_pyCol_pyDet.png
-- acs_m_bangle@ca_slot09_pyCol.png
-- acs_m_ribbon@ca_slot15_pyCol_pyDet.png
-- acs_m_ribbon@ca_slot15_pyCol.png
-- cf_m_hair_b_01_00@ca_slot06_pyCol_pyDet.png
-- cf_m_hair_b_01_00@ca_slot06_pyCol.png
-- cf_m_hair_b_21_00@ca_slot07_pyCol_pyDet.png
-- cf_m_hair_b_21_00@ca_slot07_pyCol.png
-- cf_m_hair_b_21_00@ca_slot07_pyCol_pyDet.png
-- cf_m_hair_b_21_00@ca_slot07_pyCol.png
-- cf_m_hair_b_21_00@ca_slot07_pyCol_pyDet.png
-- cf_m_hair_b_21_00@ca_slot07_pyCol.png
-- cf_m_hair_edgy@ca_slot10_pyCol_pyDet.png
-- cf_m_hair_edgy@ca_slot10_pyCol.png
-- cf_m_hair_edgy@ca_slot11_pyCol_pyDet.png
-- cf_m_hair_edgy@ca_slot11_pyCol.png
-- cf_m_hair_b_21_00@ca_slot12_pyCol_pyDet.png
-- cf_m_hair_b_21_00@ca_slot12_pyCol.png
-- cf_m_hair_b_21_00@ca_slot12_pyCol_pyDet.png
-- cf_m_hair_b_21_00@ca_slot12_pyCol.png
-- cf_m_hair_b_21_00@ca_slot12_pyCol_pyDet.png
-- cf_m_hair_b_21_00@ca_slot12_pyCol.png
-- cf_m_hair_f_20_00@ca_slot13_pyCol_pyDet.png
-- cf_m_hair_f_20_00@ca_slot13_pyCol.png
-- cf_m_hair_f_20_00@ca_slot16_pyCol_pyDet.png
-- cf_m_hair_f_20_00@ca_slot16_pyCol.png
-- cf_m_hair_f_06_00@ca_slot17_pyCol_pyDet.png
-- cf_m_hair_f_06_00@ca_slot17_pyCol.png
-- cf_m_hair_b_119_00@ca_slot18_pyCol_pyDet.png
-- cf_m_hair_b_119_00@ca_slot18_pyCol.png
-- cf_m_hair_b_119_00@ca_slot18_pyCol_pyDet.png
-- cf_m_hair_b_119_00@ca_slot18_pyCol.png
-- cf_m_hair_b_119_01@ca_slot18_pyCol_pyDet.png
-- cf_m_hair_b_119_01@ca_slot18_pyCol.png
-- cf_m_hair_b_119_01@ca_slot18_pyCol_pyDet.png
-- cf_m_hair_b_119_01@ca_slot18_pyCol.png
-- cf_m_hair_b_119_01@ca_slot18_pyCol_pyDet.png
-- cf_m_hair_b_119_01@ca_slot18_pyCol.png
-- cf_m_hair_b_21_00@ca_slot19_pyCol_pyDet.png
-- cf_m_hair_b_21_00@ca_slot19_pyCol.png
-- cf_m_hair_b_21_00@ca_slot19_pyCol_pyDet.png
-- cf_m_hair_b_21_00@ca_slot19_pyCol.png
-- cf_m_hair_b_21_00@ca_slot19_pyCol_pyDet.png
-- cf_m_hair_b_21_00@ca_slot19_pyCol.png

- To fix the above, provide the missing base file or remove it from the 'textures' element of the material

**Comment by CazzoPMX** [comment]
I thought I fixed that..... >.< Lemme look again

**Comment by CazzoPMX** [comment]
Nope, I downloaded the current release and tried it, does not happen for me anymore. 
The timestamp on my [kkpmx_core.exe] says (30.05.00:37) btw, what does yours say? (I did do some late reupload at that time, maybe it's that?)

In case you did compile something yourself, the issue was caused when I ran the *.exe while my Debug Flag was active. Haven't found out why yet, but when I did recompile it without, that error was gone too

**Comment by X3gold** [comment]
So with me it shows the same timestamp and I have taken the under Releases Latest have tested the whole thing with 10 figures but always the same error with me but with 1.7.0 just not

**Comment by CazzoPMX** [comment]
Mhm, lemme try something out then

**Comment by CazzoPMX** [comment]
I tried something else and uploaded it as "kkpmx_core_extra". Could you try again with that?

**Comment by CazzoPMX** [comment]
So, now I did the correct "extra" one. Could you try it out?

**Comment by X3gold** [comment]
Unfortunately, it does not work there either and then this message appears: **unterminated character set at position 1**

**Comment by X3gold** [comment]
**_Here again the section_**

==== Processing cf_m_body
> Extends cf_m_body#-803320
>--> Found 29 attributes to process
:: Running 'body' parser
unterminated character set at position 1
unterminated character set at position 1
unterminated character set at position 1

==== Processing cf_m_face_00
> Extends cf_m_face_00#-803316
>--> Found 29 attributes to process
:: Running 'face' parser
unterminated character set at position 1
>--> [MissingFile(LineMask)]: C:\koikatsu_model\5961/extra\cf_m_face_00_LineMask.png

==== Processing cf_m_mayuge_00
> Extends cf_m_mayuge_00#-781948
>--> Found 9 attributes to process
:: Running 'color' parser

==== Processing cf_m_noseline_00
> Extends cf_m_noseline_00#-781950
>--> Found 8 attributes to process
:: Running 'color' parser

==== Processing cf_m_eyeline_00_up
> Extends cf_m_eyeline_00_up#-781952
>--> Found 9 attributes to process
:: Running 'color' parser

==== Processing cf_m_eyeline_down
> Extends cf_m_eyeline_down#-781956
>--> Found 9 attributes to process
:: Running 'color' parser

==== Processing cf_m_hitomi_00
> Extends cf_m_hitomi_00#-781934
>--> Found 18 attributes to process
:: Running 'eye' parser
list index out of range

==== Processing cf_m_hitomi_00*1
> Extends cf_m_hitomi_00#-781936
>--> Found 18 attributes to process
:: Running 'eye' parser
list index out of range

==== Processing cf_m_tang
> Extends cf_m_tang#-797850
>--> Found 25 attributes to process
:: Running 'acc' parser
unterminated character set at position 1
unterminated character set at position 1

==== Processing cf_m_top_HMteacher_d
> Extends cf_m_top_HMteacher_d#-801636
>--> Found 21 attributes to process
:: Running 'acc' parser
unterminated character set at position 1

==== Processing cf_m_top_HMteacher_d*1
> Extends cf_m_top_HMteacher_d#-801634
>--> Found 21 attributes to process
:: Running 'acc' parser
unterminated character set at position 1

==== Processing cf_m_bot_spants
> Extends cf_m_bot_spants#-786692
>--> Found 21 attributes to process
:: Running 'acc' parser
unterminated character set at position 1

==== Processing cf_m_socks_knee01
> Extends cf_m_socks_knee01#-791284
>--> Found 21 attributes to process
:: Running 'acc' parser
unterminated character set at position 1

==== Processing cf_M_shoes_run01
> Extends cf_M_shoes_run01#-795776
>--> Found 21 attributes to process
:: Running 'acc' parser
unterminated character set at position 1

==== Processing cf_m_hair_f_ryl_002_00
> Extends cf_m_hair_f_ryl_002_00@ca_slot00
Found AlphaMask override in attr with value C:\koikatsu_model\5961\extra\cf_m_hair_f_ryl_002_00_AlphaMask@ca_slot00.png
>--> Found 21 attributes to process
:: Running 'hair' parser
unterminated character set at position 1
unterminated character set at position 1

==== Processing cf_m_hair_f_111_00
> Extends cf_m_hair_f_111_00@ca_slot01
Found AlphaMask override in attr with value C:\koikatsu_model\5961\extra\cf_m_hair_f_111_00_AlphaMask@ca_slot01.png
>--> Found 21 attributes to process
:: Running 'hair' parser
unterminated character set at position 1
unterminated character set at position 1

==== Processing cf_m_hair_f_111_00*1
> Extends cf_m_hair_f_111_00@ca_slot02
Found AlphaMask override in attr with value C:\koikatsu_model\5961\extra\cf_m_hair_f_111_00_AlphaMask@ca_slot02.png
>--> Found 21 attributes to process
:: Running 'hair' parser
unterminated character set at position 1
unterminated character set at position 1

==== Processing cf_m_hair_f_111_00*2
> Extends cf_m_hair_f_111_00@ca_slot03
Found AlphaMask override in attr with value C:\koikatsu_model\5961\extra\cf_m_hair_f_111_00_AlphaMask@ca_slot03.png
>--> Found 21 attributes to process
:: Running 'hair' parser
unterminated character set at position 1
unterminated character set at position 1

==== Processing cf_m_hair_f_111_00*3
> Extends cf_m_hair_f_111_00@ca_slot04
Found AlphaMask override in attr with value C:\koikatsu_model\5961\extra\cf_m_hair_f_111_00_AlphaMask@ca_slot04.png
>--> Found 21 attributes to process
:: Running 'hair' parser
unterminated character set at position 1
unterminated character set at position 1

==== Processing cf_m_hair_f_111_00*4
> Extends cf_m_hair_f_111_00@ca_slot05
Found AlphaMask override in attr with value C:\koikatsu_model\5961\extra\cf_m_hair_f_111_00_AlphaMask@ca_slot05.png
>--> Found 21 attributes to process
:: Running 'hair' parser
unterminated character set at position 1
unterminated character set at position 1

==== Processing cf_m_hair_f_113_00
> Extends cf_m_hair_f_113_00@ca_slot06
>--> Found 21 attributes to process
:: Running 'hair' parser
unterminated character set at position 1
unterminated character set at position 1

==== Processing cf_m_hair_b_01_00
> Extends cf_m_hair_b_01_00@ca_slot07
>--> Found 21 attributes to process
:: Running 'hair' parser
unterminated character set at position 1
unterminated character set at position 1

==== Processing cf_m_hair_f_ryl_001_00
> Extends cf_m_hair_f_ryl_001_00@ca_slot08
Found AlphaMask override in attr with value C:\koikatsu_model\5961\extra\cf_m_hair_f_ryl_001_00_AlphaMask@ca_slot08.png
>--> Found 21 attributes to process
:: Running 'hair' parser
unterminated character set at position 1
unterminated character set at position 1

==== Processing cf_m_hair_s_01_00
> Extends cf_m_hair_s_01_00@ca_slot09
>--> Found 21 attributes to process
:: Running 'hair' parser
unterminated character set at position 1
unterminated character set at position 1

==== Processing cf_m_hair_b_109_01
> Extends cf_m_hair_b_109_01@ca_slot10
>--> Found 21 attributes to process
:: Running 'hair' parser
unterminated character set at position 1
unterminated character set at position 1

==== Processing cf_m_hair_b_06_00
> Extends cf_m_hair_b_06_00@ca_slot11
>--> Found 21 attributes to process
:: Running 'hair' parser
unterminated character set at position 1
unterminated character set at position 1

==== Processing acs_m_nip_metal_threecolored
> Extends acs_m_nip_metal_threecolored@ca_slot13
>--> Found 26 attributes to process
:: Running 'acc' parser
unterminated character set at position 1
unterminated character set at position 1

==== Processing cf_m_hair_o_01_00
> Extends cf_m_hair_o_01_00@ca_slot14
>--> Found 21 attributes to process
:: Running 'hair' parser
unterminated character set at position 1
unterminated character set at position 1

==== Processing cf_m_hair_o_01_00*1
> Extends cf_m_hair_o_01_00@ca_slot15
>--> Found 21 attributes to process
:: Running 'hair' parser
unterminated character set at position 1
unterminated character set at position 1

==== Processing cf_m_hair_o_01_00*2
> Extends cf_m_hair_o_01_00@ca_slot16
>--> Found 21 attributes to process
:: Running 'hair' parser
unterminated character set at position 1
unterminated character set at position 1

==== Processing cf_m_hair_o_01_00*3
> Extends cf_m_hair_o_01_00@ca_slot17
>--> Found 21 attributes to process
:: Running 'hair' parser
unterminated character set at position 1
unterminated character set at position 1

==== Processing cf_m_hair_o_01_00*4
> Extends cf_m_hair_o_01_00@ca_slot18
>--> Found 21 attributes to process
:: Running 'hair' parser
unterminated character set at position 1
unterminated character set at position 1

==== Processing cf_m_hair_o_01_00*5
> Extends cf_m_hair_o_01_00@ca_slot19
>--> Found 21 attributes to process
:: Running 'hair' parser
unterminated character set at position 1
unterminated character set at position 1

==== Processing cf_m_hair_o_01_00*6
> Extends cf_m_hair_o_01_00@ca_slot20
>--> Found 21 attributes to process
:: Running 'hair' parser
unterminated character set at position 1
unterminated character set at position 1

==== Processing cf_m_hair_o_01_00*7
> Extends cf_m_hair_o_01_00@ca_slot21
>--> Found 21 attributes to process
:: Running 'hair' parser
unterminated character set at position 1
unterminated character set at position 1

==== Processing cf_m_hair_o_01_00*8
> Extends cf_m_hair_o_01_00@ca_slot22
>--> Found 21 attributes to process
:: Running 'hair' parser
unterminated character set at position 1
unterminated character set at position 1

==== Processing cf_m_hair_o_01_00*9
> Extends cf_m_hair_o_01_00@ca_slot23
>--> Found 21 attributes to process
:: Running 'hair' parser
unterminated character set at position 1
unterminated character set at position 1

==== Processing cf_m_hair_o_01_00*10
> Extends cf_m_hair_o_01_00@ca_slot24
>--> Found 21 attributes to process
:: Running 'hair' parser
unterminated character set at position 1
unterminated character set at position 1

==== Processing cf_m_hair_o_01_00*11
> Extends cf_m_hair_o_01_00@ca_slot25
>--> Found 21 attributes to process
:: Running 'hair' parser
unterminated character set at position 1
unterminated character set at position 1

==== Processing cf_m_hair_o_01_00*12
> Extends cf_m_hair_o_01_00@ca_slot26
>--> Found 21 attributes to process
:: Running 'hair' parser
unterminated character set at position 1
unterminated character set at position 1

==== Processing cf_m_hair_o_01_00*13
> Extends cf_m_hair_o_01_00@ca_slot27
>--> Found 21 attributes to process
:: Running 'hair' parser
unterminated character set at position 1
unterminated character set at position 1

==== Processing cf_m_hair_o_01_00*14
> Extends cf_m_hair_o_01_00@ca_slot28
>--> Found 21 attributes to process
:: Running 'hair' parser
unterminated character set at position 1
unterminated character set at position 1

==== Processing cf_m_hair_o_01_00*15
> Extends cf_m_hair_o_01_00@ca_slot29
>--> Found 21 attributes to process
:: Running 'hair' parser
unterminated character set at position 1
unterminated character set at position 1

==== Processing mf_m_accneck05
> Extends mf_m_accneck05@ca_slot30
>--> Found 26 attributes to process
:: Running 'acc' parser
unterminated character set at position 1
unterminated character set at position 1

==== Processing mf_m_accneck06
> Extends mf_m_accneck06@ca_slot31
>--> Found 26 attributes to process
:: Running 'acc' parser
unterminated character set at position 1
unterminated character set at position 1
==========
Additionally, these textures failed to generate:
-- ..\cf_m_body_pyDet.png
-- ..\cf_m_body_pyLin.png
-- ..\cf_m_body_pyOT1.png
-- ..\cf_m_face_00_pyDet.png
-- ..\cf_m_face_00_pyLin.png
-- ..\cf_m_hitomi_00_pyHL.png
-- ..\cf_m_hitomi_00+1_pyHL.png
-- ..\cf_m_tang_pyCol_pyDet.png
-- ..\cf_m_tang_pyCol.png
-- ..\cf_m_top_HMteacher_d_pyDet.png
-- ..\cf_m_top_HMteacher_d+1_pyDet.png
-- ..\cf_m_bot_spants_pyDet.png
-- ..\cf_m_socks_knee01_pyDet.png
-- ..\cf_M_shoes_run01_pyDet.png
-- cf_m_hair_f_ryl_002_00@ca_slot00_pyCol_pyDet.png
-- cf_m_hair_f_ryl_002_00@ca_slot00_pyCol.png
-- cf_m_hair_f_111_00@ca_slot01_pyCol_pyDet.png
-- cf_m_hair_f_111_00@ca_slot01_pyCol.png
-- cf_m_hair_f_111_00@ca_slot02_pyCol_pyDet.png
-- cf_m_hair_f_111_00@ca_slot02_pyCol.png
-- cf_m_hair_f_111_00@ca_slot03_pyCol_pyDet.png
-- cf_m_hair_f_111_00@ca_slot03_pyCol.png
-- cf_m_hair_f_111_00@ca_slot04_pyCol_pyDet.png
-- cf_m_hair_f_111_00@ca_slot04_pyCol.png
-- cf_m_hair_f_111_00@ca_slot05_pyCol_pyDet.png
-- cf_m_hair_f_111_00@ca_slot05_pyCol.png
-- cf_m_hair_f_113_00@ca_slot06_pyCol_pyDet.png
-- cf_m_hair_f_113_00@ca_slot06_pyCol.png
-- cf_m_hair_b_01_00@ca_slot07_pyCol_pyDet.png
-- cf_m_hair_b_01_00@ca_slot07_pyCol.png
-- cf_m_hair_f_ryl_001_00@ca_slot08_pyCol_pyDet.png
-- cf_m_hair_f_ryl_001_00@ca_slot08_pyCol.png
-- cf_m_hair_s_01_00@ca_slot09_pyCol_pyDet.png
-- cf_m_hair_s_01_00@ca_slot09_pyCol.png
-- cf_m_hair_b_109_01@ca_slot10_pyCol_pyDet.png
-- cf_m_hair_b_109_01@ca_slot10_pyCol.png
-- cf_m_hair_b_06_00@ca_slot11_pyCol_pyDet.png
-- cf_m_hair_b_06_00@ca_slot11_pyCol.png
-- ..\acs_m_nip_metal_threecolored_pyCol_pyDet.png
-- ..\acs_m_nip_metal_threecolored_pyCol.png
-- cf_m_hair_o_01_00@ca_slot14_pyCol_pyDet.png
-- cf_m_hair_o_01_00@ca_slot14_pyCol.png
-- cf_m_hair_o_01_00@ca_slot15_pyCol_pyDet.png
-- cf_m_hair_o_01_00@ca_slot15_pyCol.png
-- cf_m_hair_o_01_00@ca_slot16_pyCol_pyDet.png
-- cf_m_hair_o_01_00@ca_slot16_pyCol.png
-- cf_m_hair_o_01_00@ca_slot17_pyCol_pyDet.png
-- cf_m_hair_o_01_00@ca_slot17_pyCol.png
-- cf_m_hair_o_01_00@ca_slot18_pyCol_pyDet.png
-- cf_m_hair_o_01_00@ca_slot18_pyCol.png
-- cf_m_hair_o_01_00@ca_slot19_pyCol_pyDet.png
-- cf_m_hair_o_01_00@ca_slot19_pyCol.png
-- cf_m_hair_o_01_00@ca_slot20_pyCol_pyDet.png
-- cf_m_hair_o_01_00@ca_slot20_pyCol.png
-- cf_m_hair_o_01_00@ca_slot21_pyCol_pyDet.png
-- cf_m_hair_o_01_00@ca_slot21_pyCol.png
-- cf_m_hair_o_01_00@ca_slot22_pyCol_pyDet.png
-- cf_m_hair_o_01_00@ca_slot22_pyCol.png
-- cf_m_hair_o_01_00@ca_slot23_pyCol_pyDet.png
-- cf_m_hair_o_01_00@ca_slot23_pyCol.png
-- cf_m_hair_o_01_00@ca_slot24_pyCol_pyDet.png
-- cf_m_hair_o_01_00@ca_slot24_pyCol.png
-- cf_m_hair_o_01_00@ca_slot25_pyCol_pyDet.png
-- cf_m_hair_o_01_00@ca_slot25_pyCol.png
-- cf_m_hair_o_01_00@ca_slot26_pyCol_pyDet.png
-- cf_m_hair_o_01_00@ca_slot26_pyCol.png
-- cf_m_hair_o_01_00@ca_slot27_pyCol_pyDet.png
-- cf_m_hair_o_01_00@ca_slot27_pyCol.png
-- cf_m_hair_o_01_00@ca_slot28_pyCol_pyDet.png
-- cf_m_hair_o_01_00@ca_slot28_pyCol.png
-- cf_m_hair_o_01_00@ca_slot29_pyCol_pyDet.png
-- cf_m_hair_o_01_00@ca_slot29_pyCol.png
-- ..\mf_m_accneck05_pyCol_pyDet.png
-- ..\mf_m_accneck05_pyCol.png
-- ..\mf_m_accneck06_pyCol_pyDet.png
-- ..\mf_m_accneck06_pyCol.png

- To fix the above, provide the missing base file or remove it from the 'textures' element of the material

**Comment by CazzoPMX** [comment]
Ok, just wtf is different to before. I've added it again but with some logging, maybe it can be debugged that way.

**Comment by X3gold** [comment]
[Here again the section.txt](https://github.com/CazzoPMX/KKPMX/files/8800766/Here.again.the.section.txt)

**Comment by CazzoPMX** [comment]
Aha!

**Comment by CazzoPMX** [comment]
Please try again

**Comment by X3gold** [comment]
Great, it worked with that

**Comment by CazzoPMX** [comment]
Finally.
