### ISSUE TITLE
cf_m_body bug

### ISSUE THREAD

**Issue by X3gold** [CazzoPMX/KKPMX#9]
With 1.8.1 I noticed another bug and that is with all bodies is at the chest so a pale square after the all-in-one converter with 1.7.0 but there was no square.
![1 8 1](https://user-images.githubusercontent.com/38250861/171404086-2af200c7-4113-43ad-9220-22764cec4d5d.png)

**Comment by CazzoPMX** [comment]
Should be fixed, please try again.

**Comment by X3gold** [comment]
Thanks has worked great
